server:
  port: 8088

#    TRACE < DEBUG < INFO < WARN < ERROR
logging:
  level:
    org.springframework : INFO

spring:
  messages:
    basename: messages

  security:
    user:
      name: username
      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"


