server:
  port: 8088

#    TRACE < DEBUG < INFO < WARN < ERROR
logging:
  level:
    org.springframework : INFO

spring:
  messages:
    basename: messages

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop # none, update, validate, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    # Hibernate & SQL 둘다 사용할 것인가 (여러 데이터 초기화 기술을 사용할 것인가?)
    defer-datasource-initialization: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

  sql:
    init:
      mode: never

  security:
    user:
      name: username
      password: password
  h2:
    console:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
